force-app/main/default/objects/Logger__c/Logger__c.object-meta.xml
<CustomObject>
    <label>Integration Logger</label>
    <nameField>
        <label>In Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Loggers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Logger__c/fields/Apex_Call_Trace__c.field-meta.xml
<CustomField>
    <fullName>Apex_Call_Trace__c</fullName>
    <description>Shows were the call is being made in the code.</description>
    <inlineHelpText>Shows were the call is being made in the code.</inlineHelpText>
    <label>Apex Call Trace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logger__c/fields/API_Verb__c.field-meta.xml
<CustomField>
    <fullName>API_Verb__c</fullName>
    <label>API Verb</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Logger/Test/Wrapper/LoggerWrapperTest.cls
@isTest
public with sharing class LoggerWrapperTest {

    @isTest
    public static void test_loggerName() {
        System.debug('Started test: \'test_loggerName\'');
        Logger__c logger = TestDataFactory.createLoggerUsingDefaultValues();
        Integer loggerRecordAmount = [SELECT COUNT() FROM Logger__c];

        System.assert(logger.Name.contains(
            LoggerUtils.DEFAULT_RECORD_NAME
            )
        );
        System.assert(logger.Name.contains(
            String.valueOf(loggerRecordAmount - 1)
            )
        );
    }


    @isTest
    public static void test_statusCodeField() {
        System.debug('Started test: \'test_statusCodeField\'');
        HttpResponse response = TestDataFactory.createErrorHTTPJSONResponse();
        Logger__c logger = TestDataFactory.createLogger();
        logger = PopulateLoggerHelper.fromResponse(response, logger);

        System.assertEquals(
            response.getStatusCode(),
            logger.Response_Status_Code__c
            );
    }

    @isTest
    public static void test_APIVerbField() {
        System.debug('Started test: \'test_APIVerbField\'');
        HttpRequest request = TestDataFactory.createPostJSONRequest();
        Logger__c logger = TestDataFactory.createLogger();
        logger = PopulateLoggerHelper.fromRequest(request, logger);

        System.assertEquals(request.getMethod(), logger.API_Verb__c);
    }

    @isTest
    public static void test_EndPointField() {
        System.debug('Started test: \'test_EndPointField\'');
        HttpRequest request = TestDataFactory.createPostJSONRequest();
        Logger__c logger = TestDataFactory.createLogger();
        logger = PopulateLoggerHelper.fromRequest(request, logger);

        System.assertEquals(request.getEndpoint(), logger.End_Point__c);
    }

    @isTest
    public static void test_ApexCallTraceField() {
        System.debug('Started test: \'test_ApexCallTraceField\'');
        Logger__c logger = TestDataFactory.createLogger();
        String trace = 'LoggerWrapperTest.test_ApexCallTraceField';
        logger = PopulateLoggerHelper.putTrace(logger, trace);

        System.assertEquals(trace, logger.Apex_Call_Trace__c);
    }
}