force-app/main/default/objects/Logger__c/Logger__c.object-meta.xml
<CustomObject>
    <label>Integration Logger</label>
    <nameField>
        <label>In Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Loggers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Logger__c/fields/TEST_DO_NOT_DELTE_Account__c.field-meta.xml
<CustomField>
    <fullName>TEST_DO_NOT_DELTE_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Needed for testing purposes.</description>
    <inlineHelpText>Needed for testing purposes.</inlineHelpText>
    <label>TEST_DO_NOT_DELTE_Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Integration Loggers</relationshipLabel>
    <relationshipName>Integration_Loggers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Logger/Test/Logger Populator/loggerPopulatorTest.cls
@isTest
public with sharing class loggerPopulatorTest {


    @isTest
    public static void test_dynamicSobjectLookup() {
        System.debug('Started test: test_dynamicSobjectLookup');
        test_validLookUpConnect();
        test_invalidGivenLookUp();
    }

    private static void test_validLookUpConnect() {
        System.debug('Started test: test_validLookUpConnect');
        Account acc = TestDataFactory.createAccount();
        LoggerWrapper loggerWrapper = TestDataFactory.createDefaultLoggerWrapper();
        loggerWrapper.setSObjectLookup(
            LoggerControllerTest.TEST_LOOKUP_API_FIELD_NAME,
            acc.Id
            );
        Logger__c logger = LoggerUtils.queryThisLoggerWithAllHisFields(
            loggerWrapper.logger.Id
            );

        System.assertEquals(acc.Id, logger.TEST_DO_NOT_DELTE_Account__c);
    }

    private static void test_invalidGivenLookUp() {
        System.debug('Started test: test_invalidGivenLookUp');
        Contact con = TestDataFactory.createContact();
        LoggerWrapper loggerWrapper = TestDataFactory.createCustomControllerLoggerWrapper();
        try {
            loggerWrapper.setSObjectLookup('Contact', con.Id);
        }
        catch(LoggeCustomException e) {
            System.assertEquals(
                LoggeCustomException.tryToConnectInvalidLookup('Contact'),
                e.getMessage()
                );
        }
    }
}