force-app/main/default/objects/Logger__c/Logger__c.object-meta.xml
<CustomObject>
    <label>Integration Logger</label>
    <nameField>
        <label>In Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Loggers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Logger__c/fields/Apex_Call_Trace__c.field-meta.xml
<CustomField>
    <fullName>Apex_Call_Trace__c</fullName>
    <description>Shows were the call is being made in the code.</description>
    <inlineHelpText>Shows were the call is being made in the code.</inlineHelpText>
    <label>Apex Call Trace</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logger__c/fields/API_Verb__c.field-meta.xml
<CustomField>
    <fullName>API_Verb__c</fullName>
    <label>API Verb</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>DELETE</fullName>
            </value>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Logger__c/fields/Logger_Controller__c.field-meta.xml
<CustomField>
    <fullName>Logger_Controller__c</fullName>
    <description>Controller of this log record.</description>
    <inlineHelpText>Controller of this log record.</inlineHelpText>
    <label>Logger Controller</label>
    <referenceTo>Logg_Controller__c</referenceTo>
    <relationshipLabel>Integration Loggers</relationshipLabel>
    <relationshipName>Integration_Loggers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/Logger/Utils/PopulateLoggerHelper.cls
public with sharing class PopulateLoggerHelper {

    public static Logger__c createBasic(Logger_Controller__c controller) {
        Integer count = [SELECT count() FROM Logger__c];
        Logger__c logger  = new Logger__c(
            Name = controller.Record_names__c +  ' ' + String.valueOf(count)
        );
		insert logger;
        System.debug(
            'Created this basic Logger__c record: \n' +
            logger
        );

        return logger;
    }

    public static Logger__c fromRequest(HttpRequest request, Logger__c logger) {
        logger = putAPIVerb(request, logger);
        logger = putEndPoint(request, logger);
        System.debug('Logger After populate from HTTP request: ' + logger);

        return logger;
    }

    public static Logger__c fromResponse(HttpResponse response, Logger__c logger) {
        logger = putStatusCode(response, logger);
        System.debug('Logger After populate from HTTP response: ' + logger);

        return logger;
    }

    public static Logger__c putTrace(Logger__c logger, String apexTrace) {
        logger.Apex_Call_Trace__c = apexTrace;

        return logger;
    }

    private static Logger__c putStatusCode(HttpResponse response, Logger__c logger) {
        Integer statusFromResponse = response.getStatusCode();
        logger.Response_Status_Code__c = statusFromResponse;

        return logger;
    }

    private static Logger__c putAPIVerb(HttpRequest request, Logger__c logger) {
        String requestVerb = request.getMethod();
        logger.API_Verb__c = requestVerb;

        return logger;
    }

    private static Logger__c putEndPoint(HttpRequest request, Logger__c logger) {
        String requestEndPoint = request.getEndpoint();
        logger.End_Point__c = requestEndPoint;

        return logger;
    }
}